config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'index', to: 'neighborhoods#index'
  get 'neighborhoods/:id', to: 'neighborhoods#show', as: :neighborhood
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

def index
  if params[:name].blank?
    @neighborhoods = Neighborhood.all
  else
    @neighborhoods = Neighborhood.select do |id, neighborhood|
      neighborhood[:category] == params[:name]
    end
  end 
end
def create
  @neighborhood = Neighborhood.new(area = params[area])
end
def show

  @neighborhood = Neighborhood.all[params[:id].to_i]
end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/neighborhoods/index.html.erb
<div class="container"> 
  <h3>Search</h3>
        
  <form action = "/neighborhoods" method = "get">
    <input type = "text" name ="area" placeholder = "Shibuya" >
    <input type = "submit">
  </form>
  <% @neighborhoods.each do |id, neighborhood| %>
    <%= link_to neighborhood[:name], neighborhood_path(id) class: 'no-deco' do %>
    <% end %>
  <% end %>

</div>

app/views/neighborhoods/show.html.erb
<h1> <%= @neighborhood[:name] %> </h1>
<p>It's located in <%= @neighborhood[:area] %></p>

app/views/pages/about.html.erb
<h1>Osusume</h1>
<h2>Yusaku has many <i>osusume</i>...recommendations.  </h2>
<p>Find me in app/views/pages/about.html.erb</p>

<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="container"> 
  <h1>Welcome to Osusume! </h1>
  <h2>Add A Neighborhood</h2>

  <%= link_to "index", index_path %>
  <%= simple_form_for @neighborhood do |f| %>
  <%= f.label :neighborhood %>
  <%= f.input_field :name %>
  <%= f.hint 'No special characters please!' %>
  <%= f.button :submit %>
  <% end %>
</div>